name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt
    #     pip install apache-airflow

    - name: Format with Black
      run: |
        black airflow/dags/ predictions_api/

    - name: Lint with flake8
      run: |
        flake8 airflow/dags/ predictions_api/

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libldap2-dev libsasl2-dev

    - name: Check DAG integrity
      run: |
        pip install -r airflow/requirements.txt
        PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/airflow/dags python -c "from airflow.models import DagBag; import os; dag_folder = os.path.join(os.getcwd(), 'airflow', 'dags'); db = DagBag(dag_folder=dag_folder, include_examples=False); assert len(db.import_errors) == 0, db.import_errors"
        
    - name: Run pytest
      run: |
        pip install pytest
        pytest
